version: "3.3"
services:
  db:
    image: mysql:5.7.22
    container_name: db
    environment:
      MYSQL_DATABASE: jado
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    expose:
      - 3306
    volumes:
      - .:/flaskProject1
    restart: always

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn --bind 0.0.0.0:8000 app:app
    restart: always
    environment:
      - SQLALCHEMY_DATABASE_URI=mysql+mysqldb://root:root@db:3306/jado
    ports:
      - "8000:8000"
    volumes:
      - .:/flaskProject1






